language: python
python:
- '2.7'
install: 
- grep -v "^#" requirements.txt | xargs -L 1 pip install
script: python -m unittest discover
notifications:
  slack:
    secure: f1YnuEp5vj1dol31TlCj2DU/hGsq/JQutw/RVCerS8ikuRpHlwarDlb8IWDSwJiw0Z3YOvYZ+NFK5ssXIORWkSAtHJehJ4IJ365m5PzfMb2w/M+nLWRVquyzTlLv17XHDlPs9UA7+7n4WhPSLAESdf6B38fUQzF2CzL8Z0ukWuagdWJGa4IinkDNr7UVOc2w7GpA3Det2yuAjlL21II3a3vS8K58UGdK2GhADkHiy4S3+4qvdfA8sABHU6aC6fA5PrkBz3s6d8lAT+YAaU1FZe79TAt3CgCCeDOyeezhBbAYpj3mKCB3t7JVrauAjxCJG2JS7cxSSetmLWqQ9sdUkKQ4MMsrr1ZuJPZF66FdLPvZIsmwOdGlBadyD6ZiOzOqr1Ux/QP/aI9rKzzMKhEWcuhksBXzXy6W3yBMt5kVFs9dV6Pis7yKxy4RSh2H0y8K3ca++T227wRjhZ1wOtovHTK4jajhhWkZLgrCP9bRzm7fDitwEr8A170WPz+Nz0NCdXjk6fvbjHigbpNb5k0TwAQ8teGte4DsIlurZUNaeCp44FfQXO6NhAN4SENYo1EWsGEpBzgOgycSdZWc/0xyh9/O6r2siiWccGPpQAWMGOwyR+ZqrH3f/dABInIb8QcFFHSjO7CuBQOf9QsbGBNz1obeeYyVC8rTxGZYBfC8Re8=
